import os
import time
import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context(
        viewport={"width": 1280, "height": 720}
    )
    page = context.new_page()
    # ---------------------8
    page.goto("http://localhost:5173/")
    page.locator("html").press("Alt+s+3")
    time.sleep(0.5)
    save_screenshot(page, "screenshot1")
    page.locator("div").filter(has_text=re.compile(r"^Датчики$")).click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot2")
    page.get_by_text("Bluetooth", exact=True).click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot3")
    page.locator("div").filter(has_text=re.compile(r"^Лаборатория\(Экология\)$")).click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot4")
    page.locator("div").filter(has_text=re.compile(r"^Датчик электропроводимостиПодключен$")).get_by_role("button", name="Подключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot5")
    page.locator("div").filter(has_text=re.compile(r"^Датчик T эксп\.Подключен$")).get_by_role("button", name="Подключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot6")
    page.locator("div").filter(has_text=re.compile(r"^ИономерПодключен$")).get_by_role("button", name="Подключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot7")
    page.locator("div").filter(has_text=re.compile(r"^Датчик влажностиПодключен$")).get_by_role("button", name="Подключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot8")
    page.locator("div").filter(has_text=re.compile(r"^Датчик освещенностиПодключен$")).get_by_role("button", name="Подключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot9")
    page.get_by_role("button", name="Подключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot10")
    page.locator("div").filter(has_text=re.compile(r"^Датчик электропроводимостиОтключен$")).get_by_role("button", name="Отключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot11")
    page.locator("div").filter(has_text=re.compile(r"^Датчик T эксп\.Отключен$")).get_by_role("button", name="Отключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot12")
    page.locator("div").filter(has_text=re.compile(r"^ИономерОтключен$")).get_by_role("button", name="Отключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot13")
    page.locator("div").filter(has_text=re.compile(r"^Датчик влажностиОтключен$")).get_by_role("button", name="Отключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot14")
    page.locator("div").filter(has_text=re.compile(r"^Датчик освещенностиОтключен$")).get_by_role("button", name="Отключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot15")
    page.get_by_role("button", name="Отключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot16")
    page.locator("div").filter(has_text=re.compile(r"^Датчик электропроводимости$")).click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot17")
    page.locator("div").filter(has_text=re.compile(r"^Датчик T эксп\.$")).click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot18")
    page.locator("div").filter(has_text=re.compile(r"^Иономер$")).click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot19")
    page.locator("div").filter(has_text=re.compile(r"^Датчик влажности$")).click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot20")
    page.get_by_text("Датчик освещенности").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot21")
    page.get_by_text("Датчик Т окр.").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot22")
    page.get_by_text("Настройки эксперимента").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot23")
    page.locator("div").filter(has_text=re.compile(r"^СекундМинут$")).get_by_role("combobox").select_option("1")
    time.sleep(0.5)
    save_screenshot(page, "screenshot24")
    page.locator("div").filter(has_text=re.compile(r"^Формат времениСекундомерММ:ССЧЧ:ММ$")).get_by_role("combobox").select_option("0")
    time.sleep(0.5)
    save_screenshot(page, "screenshot25")
    page.locator("div").filter(has_text=re.compile(r"^Формат времениСекундомерММ:ССЧЧ:ММ$")).get_by_role("combobox").select_option("2")
    time.sleep(0.5)
    save_screenshot(page, "screenshot26")
    page.locator("div").filter(has_text=re.compile(r"^Вид графика по умолчаниюВручнуюЛинияЛиния с точкамиТочки$")).get_by_role("combobox").select_option("1")
    time.sleep(0.5)
    save_screenshot(page, "screenshot27")
    page.locator("div").filter(has_text=re.compile(r"^Вид графика по умолчаниюВручнуюЛинияЛиния с точкамиТочки$")).get_by_role("combobox").select_option("2")
    time.sleep(0.5)
    save_screenshot(page, "screenshot28")
    page.locator("div").filter(has_text=re.compile(r"^Вид графика по умолчаниюВручнуюЛинияЛиния с точкамиТочки$")).get_by_role("combobox").select_option("3")
    time.sleep(0.5)
    save_screenshot(page, "screenshot29")
    page.locator("div").filter(has_text=re.compile(r"^Связка датчиков$")).click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot30")
    page.get_by_placeholder("Название").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot31")
    page.get_by_placeholder("Название").fill("1")
    time.sleep(0.5)
    save_screenshot(page, "screenshot32")
    page.get_by_role("button", name="Создать").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot33")
    page.get_by_role("button", name="Перейти").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot34")
    page.locator("div").filter(has_text=re.compile(r"^Датчик электропроводимостиОтключен$")).get_by_role("button", name="Отключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot35")
    page.locator("div").filter(has_text=re.compile(r"^Датчик T эксп\.Отключен$")).get_by_role("button", name="Отключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot36")
    page.locator("div").filter(has_text=re.compile(r"^ИономерОтключен$")).get_by_role("button", name="Отключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot37")
    page.locator("div").filter(has_text=re.compile(r"^Датчик влажностиОтключен$")).get_by_role("button", name="Отключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot38")
    page.locator("div").filter(has_text=re.compile(r"^Датчик освещенностиОтключен$")).get_by_role("button", name="Отключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot39")
    page.get_by_role("button", name="Отключен").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot40")
    page.get_by_text("Сеанс автономной работы").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot41")
    page.get_by_role("button", name="Запустить сеанс автономной работы").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot42")
    page.get_by_role("button", name="⚒️ Работа с данными сеанса").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot43")
    page.locator(".sc-gueYoa").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot44")
    page.locator("div").filter(has_text=re.compile(r"^Калибровка$")).click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot45")
    page.get_by_role("textbox").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot46")
    page.get_by_role("textbox").fill("12345")
    time.sleep(0.5)
    save_screenshot(page, "screenshot47")
    page.get_by_role("button", name="Подтвердить").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot48")
    page.locator("div").filter(has_text=re.compile(r"^Датчик T эксп\.Калибровать$")).get_by_role("button", name="Калибровать").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot49")
    page.locator("span").filter(has_text="Калибровка датчика Датчик T эксп.").get_by_role("button").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot50")
    page.locator("div").filter(has_text=re.compile(r"^ИономерКалибровать$")).get_by_role("button", name="Калибровать").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot51")
    page.locator("span").filter(has_text="Калибровка датчика Иономер").get_by_role("button").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot52")
    page.locator("div").filter(has_text=re.compile(r"^Датчик влажностиКалибровать$")).get_by_role("button", name="Калибровать").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot53")
    page.locator("span").filter(has_text="Калибровка датчика Датчик влажности").get_by_role("button").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot54")
    page.locator("div").filter(has_text=re.compile(r"^Датчик освещенностиКалибровать$")).get_by_role("button", name="Калибровать").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot55")
    page.locator("span").filter(has_text="Калибровка датчика Датчик освещенности").get_by_role("button").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot56")
    page.locator("div").filter(has_text=re.compile(r"^Датчик Т окр\.Калибровать$")).get_by_role("button", name="Калибровать").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot57")
    page.locator("span").filter(has_text="Калибровка датчика Датчик Т окр.").get_by_role("button").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot58")
    page.get_by_text("О программе").click()
    time.sleep(0.5)
    save_screenshot(page, "screenshot59")

    # ---------------------end
    context.close()
    browser.close()


def save_screenshot(page, name):
    project_root = os.getcwd()  # Получаем текущую рабочую директорию (корень проекта)
    screenshots_dir = os.path.join(project_root, "screenshots_test")
    os.makedirs(screenshots_dir, exist_ok=True)
    screenshot_path = os.path.join(screenshots_dir, f"{name}.png")
    page.screenshot(path=screenshot_path)


with sync_playwright() as playwright:
    run(playwright)
    # time.sleep(0.5)
    # save_screenshot(page, "screenshot")
